model:
  type: diffab
  res_feat_dim: 128
  pair_feat_dim: 64
  diffusion:
    num_steps: 100
    eps_net_opt:
      num_layers: 6
  train_structure: true
  train_sequence: true

train:
  loss_weights:
    rot: 1.0
    pos: 1.0
    seq: 1.0
  max_iters: 16_000
  val_freq: 1000
  batch_size: 20
  seed: 2022
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 0.0005
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 5.e-6

dataset:
  train:
    type: sabdab
    summary_path: ./data/sabdab_summary_all.tsv
    chothia_dir: ./data/all_structures/chothia
    processed_dir: ./data/processed_com
    split: train
    transform:
    - type: mask_single_cdr
      selection: CDR3
    - type: split_chains
#    - type: patch_around_anchor
    - type: patch_cdr_epitope
  val:
    type: sabdab
    summary_path: ./data/sabdab_summary_all.tsv
    chothia_dir: ./data/all_structures/chothia
    processed_dir: ./data/processed_com
    split: val
    transform:
    - type: mask_single_cdr
      selection: CDR3
    - type: split_chains
#    - type: patch_around_anchor
  save_emb:
    type: sabdab
    summary_path: ./data/sabdab_summary_all.tsv
    chothia_dir: ./data/all_structures/chothia
    processed_dir: ./data/processed_com
    split: save_emb
    transform:
    - type: mask_single_cdr
      selection: CDR3
    - type: split_chains
#    - type: patch_around_anchor
